### PR TITLE
Hutch theme

### PR DESCRIPTION
**Pull request by vsriram24**
Update the baseline Shiny app to include Fred Hutch theming / improved aesthetics

### CODE REVIEW

**Comment by seankross** [comment]
Does work on this branch build upon your work in `ingest-scp`? If so, change the base branch to `ingest-scp`. If not, let's talk about how to make sure you're not duplicating changes across PRs.

**Comment by seankross** [comment]
I like the Hutch theming! The dream of Oncarto is that anyone could grab this and spin it up for their own cancer center. I think we should separate out the Hutch theming so that the version we run here has it, but we don't force it on everyone else. Let's try to think about this creatively so that other people can look at the Hutch theming as an example for their own theming. Like can we boil the theming down to a function that we drop into the app? Or as an argument to `oncarto::run_app()`? Once we figure out the PR base I will have more specific suggestions.

**Comment by vsriram24** [comment]
@seankross Hutch theming is ready for your review again. I brought all of the HTML in the app out into the provided CSS file so that users can just update their own CSS file if they want different colors/fonts in the app. I also have a "set-aesthetics" function now that lets users change metadata about their provided logo / app title, so that they could use their own content.

Let me know if it would be helpful for us to walk through this together in person before you start your code review, as well as when you think it would be helpful to bring @codebeaker in.

**Comment by seankross** [comment]
@vsriram24 is this the right base branch? Or should we be merging this into `dev`?

**Comment by vsriram24** [comment]
@seankross good catch - I've fixed the base branch to `dev`. Thank you!

**Pull request merged**
